version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/mernapp    # if using mongoose in code
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true   # optionally fix file watching in Docker
    depends_on:
      - backend

  mongo:
    image: mongo:6   # Use official MongoDB image (latest v6)
    volumes:
      - mongo-data:/data/db
    # no ports: Mongo is used internally only (not exposed to host)

volumes:
  mongo-data:

